# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_date', models.DateField(default=datetime.date(2016, 3, 22))),
                ('vendor', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('grind', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('date_roasted', models.DateField(default=datetime.date(2016, 3, 22))),
                ('date_ground', models.DateField(default=datetime.date(2016, 3, 22))),
                ('ground_by', models.CharField(max_length=200)),
                ('hints_of', models.CharField(max_length=200)),
                ('roast_type', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('varietal', models.CharField(max_length=200)),
                ('altitude', models.CharField(max_length=200)),
                ('farmer_question', models.TextField()),
                ('farmer_answer', models.TextField()),
                ('tasting_notes_flavour', models.CharField(max_length=200)),
                ('tasting_notes_sweetness', models.CharField(max_length=200)),
                ('tasting_notes_acidity', models.CharField(max_length=200)),
                ('tasting_notes_mouthfeel', models.CharField(max_length=200)),
                ('pact_reviewer_name', models.CharField(max_length=200)),
                ('pact_reviewer_says', models.TextField()),
                ('kettle_boiled', models.BooleanField()),
                ('water_type', models.CharField(max_length=200)),
                ('kettle_cooldown_time', models.IntegerField(default=0)),
                ('water_temperature', models.IntegerField(default=0)),
                ('brew_method', models.CharField(max_length=200)),
                ('brew_submethod', models.CharField(max_length=200)),
                ('inspired_by', models.CharField(max_length=200)),
                ('coffee_amount', models.CharField(max_length=200)),
                ('initial_water_volume', models.CharField(max_length=200)),
                ('stir_amount', models.CharField(max_length=200)),
                ('bloom_time', models.CharField(max_length=200)),
                ('second_water_volume', models.CharField(max_length=200)),
                ('second_water_time', models.CharField(max_length=200)),
                ('plunge_time', models.CharField(max_length=200)),
                ('plunge_into', models.CharField(max_length=200)),
                ('repour_into_mug', models.BooleanField()),
                ('hot_water_added', models.BooleanField()),
                ('milk_added', models.BooleanField()),
                ('sugar_added', models.BooleanField()),
                ('score', models.IntegerField(default=0)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
