# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20160322_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='brew_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='brew',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
