# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20160322_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
