# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160328_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brew',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='country',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='date_ground',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='date_roasted',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='farmer_answer',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='farmer_question',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='grind',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='ground_by',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='hints_of',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='name',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='pact_reviewer_name',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='pact_reviewer_says',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='process',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='roast_type',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='tasting_notes_acidity',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='tasting_notes_flavour',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='tasting_notes_mouthfeel',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='tasting_notes_sweetness',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='varietal',
        ),
        migrations.RemoveField(
            model_name='brew',
            name='vendor',
        ),
    ]
